### ISSUE TITLE
Move from rome to biome, since rome is discontinued, and add circular imports (organizeImports)

### ISSUE THREAD

**Issue by brunoguerios** [balancer/b-sdk#133]
Circular imports caused build issues before.
This lint was suggested by Alberto in the API:
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md
Will likely need a bunch of refactoring if implemented.

**Comment by lgahdl** [comment]
The Rome package has been discontinued, we'll need to move to biome:

Source:
https://twitter.com/rometools/status/1697661266473386438
https://biomejs.dev/blog/annoucing-biome/#i-still-use-the-rome-package-what-should-i-do
