### ISSUE TITLE
Support Nested Weighted Pools

### ISSUE THREAD

**Issue by brunoguerios** [balancer/b-sdk#135]
Currently beets API does not support Nested Weighted Pools.
As soon as the API is updated, b-sdk API client should be updated as well.

Note: add/remove liquidity nested logic already supports it. It's just the API client that needs to be updated.

**Comment by brunoguerios** [comment]
@franzns - let me know once you have any updated on this on the API side, plz?

**Comment by franzns** [comment]
> @franzns - let me know once you have any updates on this on the API side, plz?

afaik, it is TBD whether we want to support nested weighted pools at all. @danielmkm has there been a conclusion yet?

**Comment by franzns** [comment]
I think the only real pool is this one https://app.balancer.fi/#/ethereum/pool/0x3dd0843a028c86e0b760b1a76929d1c5ef93a2dd000200000000000000000249 

it would IMO be totally ok to join that with a BPT and auraBAL and receive a BPT and auraBAL when exiting.

**Comment by brunoguerios** [comment]
In any case, the add/remove liquidity is able to handle such case - if we ever decide to fully support it, all we need is for the api to be updated.
