### ISSUE TITLE
SOR v3 Scaffold

### ISSUE THREAD

**Issue by brunoguerios** [balancer/b-sdk#190]
Prepare b-sdk to support both v2 and v3 implementation

**Comment by sarthak1dev** [comment]
hey i am trying to understand smart routing for a technical article, could you point to the SOR code?

**Comment by brunoguerios** [comment]
@sarthak1dev - you should be able to find it here: https://github.com/balancer/b-sdk/blob/main/src/sor.ts

**Comment by brunoguerios** [comment]
Closing this as the SOR was moved to the api
