### ISSUE TITLE
Review token ordering for V3 functions

### ISSUE THREAD

**Issue by johngrantuk** [balancer/b-sdk#273]
AFAIU in V3 tokens are no longer sorted by address but instead by the order of tokens being passed when the pool is created.
In V3 weighted pool creation we are sorting the tokens by address [here](https://github.com/balancer/b-sdk/blob/6e76dd2365324e5f9cc4e298284ce985a658c28d/src/entities/createPool/createPoolV3/weighted/createPoolWeighted.ts#L31) before creating the pool. 
This could perhaps lead to unexpected behaviour for users? Is there anywhere else we're doing similar?

**Comment by brunoguerios** [comment]
This affects add liquidity implementation as well. I pinged SC team to discuss the best approach here.

**Comment by brunoguerios** [comment]
After discussing this with SC team, we decided to keep V2 pattern and apply token sorting to V3 as well, so I'm closing this task as it's no longer needed.
