### ISSUE TITLE
Support - b-sdk recovery exits malfunctioning for Phantom Stable pools (Composable Stable V0)

### ISSUE THREAD

**Issue by lgahdl** [balancer/b-sdk#279]
Pool: https://app.balancer.fi/#/ethereum/pool/0x7b50775383d3d6f0215a8f290f2c9e2eebbeceb20000000000000000000000fe
Impersonated Address:
0x26743984e3357eFC59f2fd6C1aFDC310335a61c9
BptIn:
137222.962994584164061051

![Image](https://github.com/balancer/b-sdk/assets/50002794/20d6ac6c-02c7-47a4-acd4-db1e5400d51c)

**Comment by agualis** [comment]
Hey @lgahdl 

I also found the same problem in this Composable Stable pool: 

Pool swETH/Boosted Aave v3 WETH

ID: 0xae8535c23afedda9304b03c68a3563b75fc8f92b0000000000000000000005a0

Impersonated Address: 
0x489A3AA83C1F204f0647C67C9FBF3e7Ee1463Bc5

bptIn:
{rawAmount: 27428748977142483n, decimals: 18, address: '0xae8535c23afedda9304b03c68a3563b75fc8f92b'}

Error: 
```
app-index.js:34 ContractFunctionExecutionError: The contract function "queryExit" reverted with the following reason:
Not implemented

Contract Call:
  address:   0xE39B5e3B6D74016b2F6A9673D7d7493B6DF549d5
  function:  queryExit(bytes32 poolId, address sender, address recipient, (address[] assets, uint256[] minAmountsOut, bytes userData, bool toInternalBalance))
  args:               (0xae8535c23afedda9304b03c68a3563b75fc8f92b0000000000000000000005a0, 0x0000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000, {"assets":["0xae8535c23afedda9304b03c68a3563b75fc8f92b","0xbb6881874825e60e1160416d6c426eae65f2459e","0xf951e335afb289353dc249e82926178eac7ded78"],"minAmountsOut":["0","0","0"],"userData":"0x00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000061724d476a7ad3","toInternalBalance":false})

Docs: https://viem.sh/docs/contract/simulateContract
Version: viem@2.7.6
    at getContractError (getContractError.js:34:12)
    at simulateContract (simulateContract.js:83:98)
    at async doRemoveLiquidityQuery (index.mjs:13894:7)
    at async RemoveLiquidityComposableStable.query (index.mjs:14083:25)
    at async ProportionalRemoveLiquidityHandler.simulate (ProportionalRemoveLiquidity.handler.ts:41:28)
```

**Comment by brunoguerios** [comment]
Here's what I found out digging a bit deeper on this issue:
1. queryExit does not support recovery exits
2. current b-sdk implementation workaround this by querying proportional exit, which should return the same results
3. pools reported here are within the list of bricked pools that had their rate provider updated to revert when getRate is called
4. queryExit (proportional) fail/revert because they attempt to call getRate on these pools

Not sure what would be the best approach to handle these cases, but essentially we're not able to query recovery exits for these pools.

**Comment by johngrantuk** [comment]
@brunoguerios - probably worth confirming with SC guys that V3 will support queries on recovery exits.
