### ISSUE TITLE
Sequential tests are affecting each other

### ISSUE THREAD

**Issue by brunoguerios** [balancer/b-sdk#291]
Currently sequential tests are affecting each other because they are using the same anvil fork.

One example is when testing removeLiquidity operations and the pool gets drained between tests, causing further tests to fail.

Ideally, each test should be encapsulated and not affect other test scenarios.

This task aims to investigate/understand this better, keeping in mind that changes like these could reduce test perfomance and we should really try to optimize for speed.

Possible approaches:
1. use start/stopAnvilFork on each test
2. [reset](https://viem.sh/docs/actions/test/reset#reset) forks between tests (this one seems to increase test time significantly, so maybe not the best option)

**Comment by brunoguerios** [comment]
Nice 👏  I'll start using this from now on 😃

**Comment by johngrantuk** [comment]
Will close this as we are using the new method now.
