### ISSUE TITLE
Price Impact fails when input has too many decimals

### ISSUE THREAD

**Issue by brunoguerios** [balancer/b-sdk#326]
See details in [this FE PR](https://github.com/balancer/frontend-v3/pull/660)

In summary: using proportional inputs to calculate price impact on Add Liquidity Unbalanced with 18 decimals is causing Price Impact code to fail

We should investigate and prevent that from happening

**Comment by abhinavk454** [comment]
I would like to work on this issue.

**Comment by brunoguerios** [comment]
Hey @abhinavk454 👋 
Thanks for your interest, but we're handling these tasks internally for now.
We'll reach out in case that changes in the future.
Cheers!

**Comment by brunoguerios** [comment]
@agualis - do you know if this issue is still happening? 
We had a fix for near proportional inputs being used to calculate Price Impact for Add Liquidity Unbalanced, but I'm not sure if it fixed this one as well.

**Comment by agualis** [comment]
@brunoguerios We were trimming to 10 decimals to workaround the issue. 
I [removed that code here](https://github.com/balancer/frontend-v3/pull/965) and I couldn't reproduce it anymore (tested proportional + unbalanced in 3 different pools) so I guess it is fixed.
