### ISSUE TITLE
SDK V3: Update to 5th testnet deployment of contracts

### ISSUE THREAD

**Issue by MattPereira** [balancer/b-sdk#334]
### Overview
We need to update the contract addresses and ABIs to be the latest deployments. 

### Resources
- Example PR  :point_right:  https://github.com/balancer/b-sdk/pull/319
- [Latest contract addresses from 5th testnet deployment](https://github.com/balancer/pvt-deployments/blob/d38e57bfd22dc021b1209de871a51d61ea6c550b/tasks/v3-vault-5/output/sepolia.json)
- [Verified contract info on Tenderly](https://dashboard.tenderly.co/balancer/v3/contracts) (grab ABIs here)
- Mock Pool Deployments used for tests
```
  "B-50BAL-50WETH": "0x7CF221Fa36584f59A4F7FD7b946B8571c78E3692",
  "B-50DAI-50USDC": "0xf45f9638460e65173eAc117d9CE569cC0D561bF6",
  "B-50BAL-50DAI": "0xf6C927cAD5Fe9eB259e59ef604FC74532075dD97",
  "B-50WETH-50USD": "0xB1205100512690D5d51AddFf12AE0Ed99BCe80e8"
```

**Comment by MattPereira** [comment]
### Blocker
A bunch of tests are failing because of `ContractFunctionExecutionError`
![image](https://github.com/balancer/b-sdk/assets/73561520/3b9d234a-1cfe-491b-ae67-7125e8940d6a)


Here are results of verifying the same call from screenshot above but using foundry's `cast call` instead. Its interesting that it doesnt return 0x when the address is a valid pool but does with my phony `0x42069` comparison

![Screenshot from 2024-06-24 15-25-02](https://github.com/balancer/b-sdk/assets/73561520/ddb0f6e9-f328-4575-821a-6529e70b9cb5)

**Comment by MattPereira** [comment]
### Blocker
Creating weighted pools is failing because of missing "PoolCreated" event
![image](https://github.com/balancer/b-sdk/assets/73561520/aa963fc3-13ca-485b-8931-149d909922de)

Some how the tx is successful but the receipt contains no event logs :smiling_face_with_tear: 
![image](https://github.com/balancer/b-sdk/assets/73561520/887abd2b-2f28-4ba4-98b1-37832ccb1df0)

**Comment by johngrantuk** [comment]
> ### Blocker
> 
> A bunch of tests are failing because of `ContractFunctionExecutionError` ![image](https://private-user-images.githubusercontent.com/73561520/342511363-3b9d234a-1cfe-491b-ae67-7125e8940d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDI4ODYsIm5iZiI6MTcxOTMwMjU4NiwicGF0aCI6Ii83MzU2MTUyMC8zNDI1MTEzNjMtM2I5ZDIzNGEtMWNmZS00OTFiLWFlNjctNzEyNWU4OTQwZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4MDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwOTY3NWYxY2RhYjM5MzQ3YTA3MGU3OWVkM2FkMjFjNTZiNDdlZjMyYzA3ZWViNTFmYjhmODYyYmIxZjkxZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9jRy4Oqct5fveUnpHmOyv4wfTWZd8Go8kT0QQO52Gg)
> 
> I have verified that the address is a contract, the params seem fine, and the pool contract almost certainly has the "allowance" function
> 
> Here are results of making the same call from screenshot above using foundry's `cast call` instead. Its interesting that it doesnt return `no data ("0x")` when the address is a valid pool but does with my intentional `0x42069...` spoof
> 
> ![Screenshot from 2024-06-24 15-25-02](https://private-user-images.githubusercontent.com/73561520/342511440-ddb0f6e9-f328-4575-821a-6529e70b9cb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDI4ODYsIm5iZiI6MTcxOTMwMjU4NiwicGF0aCI6Ii83MzU2MTUyMC8zNDI1MTE0NDAtZGRiMGY2ZTktZjMyOC00NTc1LTgyMWEtNjUyOWU3MGI5Y2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4MDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZWQ2YWM2YmJmZTg5MzczY2I0YjRlZmI2MjI2NmM2MjEwOTE2MDE3NjJhYzdiYzBmODQxMjlmZDVjYjQwNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wD68CJtL6avMpj3EjEwWo7HP631iXawgspPUGTlnhmk)
> 
> This phenomenon is also happening for all of the router queries 🤔 ![image](https://private-user-images.githubusercontent.com/73561520/342512173-a1a27adb-7aca-42da-a354-76e6943d2327.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDI4ODYsIm5iZiI6MTcxOTMwMjU4NiwicGF0aCI6Ii83MzU2MTUyMC8zNDI1MTIxNzMtYTFhMjdhZGItN2FjYS00MmRhLWEzNTQtNzZlNjk0M2QyMzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4MDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYWE1MTIxYTQ2ZmI5ZDA2M2U5MzAxODdjOTc0N2YzNTQ1ZDhlOThiNmYzZDJmMjMxZDIwMWQxNzYzZDQ1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2IxEk1-qdUc4jzwgH3wXSL1Nv5qb9ABvKGShahCN_iw)

This is an annoying one that sometimes pops up, once you've experienced it once it'll probably stick in your head! If you check `anvil-global-setup.ts` you'll see the current `forkBlockNumber` is actually set for a block before the contract was deployed, I updated that to: `forkBlockNumber: 6178545n,` and it fixes the removeLiquidity tests at least. There still seems to be issues elsewhere though...

**Comment by johngrantuk** [comment]
> ### Blocker
> 
> Creating weighted pools is failing because of missing "PoolCreated" event ![image](https://private-user-images.githubusercontent.com/73561520/342583763-aa963fc3-13ca-485b-8931-149d909922de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDI4ODYsIm5iZiI6MTcxOTMwMjU4NiwicGF0aCI6Ii83MzU2MTUyMC8zNDI1ODM3NjMtYWE5NjNmYzMtMTNjYS00ODViLTg5MzEtMTQ5ZDkwOTkyMmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4MDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNDE0ZjZjOWYxNTViZWJmOWM0NTU1OWNlNjI5Y2EyZWM2YWQ0YmQ5MWQwZTM1YjZhNTZhOGYyYTVlMTA5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZwadL0T5uU4TCqqecmDI0OmAYAamuNBoMhPc_mfm4MI)
> 
> Some how the tx is successful but the receipt contains no event logs 🥲 ![image](https://private-user-images.githubusercontent.com/73561520/342583926-887abd2b-2f28-4ba4-98b1-37832ccb1df0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDI4ODYsIm5iZiI6MTcxOTMwMjU4NiwicGF0aCI6Ii83MzU2MTUyMC8zNDI1ODM5MjYtODg3YWJkMmItMmYyOC00YmE0LTk4YjEtMzc4MzJjY2IxZGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4MDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYzBhZTc0ZWNjMmE5YTNhZTRhY2IzNjY0OGUwYTAwZDkxZjFhNDYzYjMwY2U2Y2Y2YzJiYzg4YzQ3N2NkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.74OLBzsjmueDjp6m8Wqypvb1zFt5JgO0ap47DJZw0Ts)

Worth digging into this a bit more:
* confirm in mono-repo that we still expect the event
* try a tenderly simulation to see if it happens there
Let us know what you find!

**Comment by brunoguerios** [comment]
About checking if a pool was properly created by parsing an event message. 
I've always felt like this is a workaround that could be improved. 
Can we influence this somehow? 
Ask them to return the pool address (or any other info we might need)?

**Comment by johngrantuk** [comment]
> About checking if a pool was properly created by parsing an event message. I've always felt like this is a workaround that could be improved. Can we influence this somehow? Ask them to return the pool address (or any other info we might need)?

Not sure quite what you mean here but if there is a way to make things better (especially for builders) we should definitely raise it 👍

**Comment by brunoguerios** [comment]
> Not sure quite what you mean here but if there is a way to make things better (especially for builders) we should definitely raise it 👍

We're currently parsing `poolAddress` from the `poolCreatedEvent` message.
This seems a bit odd to me, as I'd expect the `create` method to already return `poolAddress`.
My suggestion was to ask the SC to add it to the output of the function, but as a matter of fact, I just looked at the ABI of the pool factory and `create` does return `poolAddress`, so I'm not really sure why we're not getting it directly from there.
I believe it's better to rely on the output of the function instead of relying on the event message.

**Comment by MattPereira** [comment]
> I believe relying on the output of the function is better than relying on the event message
@brunoguerios Can you help me understand why? 

The event is arguably more important since its what's actually used for indexing the data, but also i guess that testing prolly happens on monorepo huh

**Comment by brunoguerios** [comment]
I'd say it's more like a general feeling. The question that triggered this was:
> confirm in mono-repo that we still expect the event

Event message just seems more loosely coupled with the function itself than its own output.
Anyway - I don't think this is huge problem. Just something that bugged me for a while.
If you guys think the event message is reliable enough, I'd say it's ok to stick with it 👍

**Comment by MattPereira** [comment]
### Blocker
The 'multi-hop swap' for the swapV3 Integration tests are all still failing. I copy/pasted the args from the failing test output to simulate with tenderly where the transaction is successful :thinking: 

#### QuerySwapExactIn
[:eyes: Tenderly Simulation of `querySwapExactIn()`](https://dashboard.tenderly.co/balancer/v3/simulator/1e5c70f2-e371-417f-affa-de71ac44abc7)

![image](https://github.com/balancer/b-sdk/assets/73561520/c0b6960f-5bcf-43e9-b446-b5e0d2e7afcb)

#### QuerySwapExactOut
[:eyes: Tenderly Simulation of `querySwapExactOut()`](https://www.tdly.co/shared/simulation/349d59e8-d990-42c2-9ace-cefd79bfb0a0)

![image](https://github.com/balancer/b-sdk/assets/73561520/d2987abb-c996-43f5-a377-7941981d3a58)

**Comment by MattPereira** [comment]
I realized its passing on Tenderly cus it uses latest block number by default. Sorry I still don't have a great handle on how the block numbers work. I get that it has to be a block number after deployment of the contract cus all tests execute at the given block number right?
