### ISSUE TITLE
Re-enable swap tests with join/exits

### ISSUE THREAD

**Issue by johngrantuk** [balancer/b-sdk#351]
Once issues seeding nested liquidity pools are fixed.
test/entities/swaps/v3/swapV3.integration.test.ts

**Comment by brunoguerios** [comment]
This [query](https://api.studio.thegraph.com/proxy/31386/balancer-v3-sepolia-6th/version/latest/graphql?query=%7B%0A%09pools%28%0A++++where%3A+%7B%0A++++++tokens_%3A+%7B%0A++++++++nestedPool_not%3A+null%0A++++++%7D%0A++++%7D%0A++%29+%7B%0A%09++id%0A++++isInitialized%0A++++tokens+%7B%0A++++++symbol%0A++++++balance%0A++++%7D%0A%09%7D%0A%7D%0A) is useful to get all nested pools for testnet deployment 6.
All this task requires is to:
- update pool addresses
- update swap tests blockNumber
- update swap tests with new amounts
- make sure tests are passing as expected
