### ISSUE TITLE
Add Liquidity Unbalanced example is not working as expected

### ISSUE THREAD

**Issue by brunoguerios** [balancer/b-sdk#405]
queryAddLiquidityUnbalanced is failing on my end.

I'm assuming it's some sort of mismatch between testnet deployments.
SDK is currently using testnet deployment 7, while test api seems to not be supporting it yet.

A suggestion would be to update the example with a v2 pool on a chain that is no sepolia, so we don't have to keep updating the example content on every new testnet deployment.

**Comment by johngrantuk** [comment]
Closing in favour of a wider examples refactor/check ticket now we have released.
