### ISSUE TITLE
V2 Single Token Exit Reverting

### ISSUE THREAD

**Issue by johngrantuk** [balancer/b-sdk#414]
User: 0xf2267EeA216037d29e4e7206183caB1640706117
Pool: https://balancer.fi/pools/gnosis/v2/0x4d7d7b769cc617a00ed98ff3426c350a50e727120001000000000000000000c1/remove-liquidity
Non-nested
5 asset pool
To a single token USDC.e: 0x2a22f9c3b484c3629090feed35f17ff8f88f76f0
humanBptIn: 6228.440443578208593374

The same BalancerQueries query is run when we call simulate and same BAL#306 error happens:
https://dashboard.tenderly.co/agualis/v3/simulator/b6cc9e01-89d2-4092-a5f0-c9dca9f50679

Error in WeightedMath:
```
// Calculate the factor by which the invariant will decrease after burning BPTAmountIn
uint256 invariantRatio = bptTotalSupply.sub(bptAmountIn).divUp(bptTotalSupply);
_require(invariantRatio >= _MIN_INVARIANT_RATIO, Errors.MIN_BPT_IN_FOR_TOKEN_OUT);
```

**Comment by guloguy** [comment]
Ya

Esteban Angulo

**Comment by johngrantuk** [comment]
The issue is that Weighted pools never allow for trades that are larger than 30% of the pool's balance and a similar check is applied to the invariant on non-proportional add/removes. So the single asset exit is basically seen as a swap and in this case the user is trying to exit with > 30% so it reverts. Proportional exits don't have that condition so all is fine there. Its only going to be an edge case on low liquidity pools.

FE going to change: > 25% block single asset exits and show warning
