### ISSUE TITLE
V3 Proportional Adds Issue

### ISSUE THREAD

**Issue by johngrantuk** [balancer/b-sdk#437]
Investigate issue mentioned by Alberto.
- Initial thought is this could be similar to CowAmm issues and we need to replicate maths 100%. Currently there may still be changes to maths (and between deploy versions) so would wait until that is final.

From Alberto:

The [v3 proportional adds and removes are merged](https://github.com/balancer/frontend-v3/pull/1157) and working as expected but I found one issue in the permit2 signature step:
I hit [this AMOUNT_OUT_OF_RANGE ](https://github.com/balancer/b-sdk/blob/c00da93260806a7dfdbf634512e151d6bba0dc8f/src/entities/permit2Helper/allowanceTransfer.ts#L188)error when setting the amountsIn to MaxAllowanceTransferAmount (MaxUint160)  in the Permit2Helper.signAddLiquidityApproval call.
I didn’t debug the SDK code but saw that I was setting:
MaxUint160 -> 1461501637330902918203684832716283019655932542975n
but the number that you check [here](https://github.com/balancer/b-sdk/blob/c00da93260806a7dfdbf634512e151d6bba0dc8f/src/entities/permit2Helper/allowanceTransfer.ts#L188) is slightly bigger:
1462963138968233821121888517548999302675588475517n (edited) 
Given that the proportional amount do not have slippage, I guess that It could be the fees being added? (I can check the code if you don’t have the answer)
If that’s the case, we should detect that the user is allowing the maximum MaxUint160 and avoid adding the fee.
For now. I’m just using MaxUint159 (which works like max in practice) so no hurries at all

**Comment by brunoguerios** [comment]
Are we still expecting changes to maths or is it ok to work on this issue?

**Comment by johngrantuk** [comment]
> Are we still expecting changes to maths or is it ok to work on this issue?

Juani said yesterday that the current testnet deployment should be final maths.

**Comment by brunoguerios** [comment]
Ok, I see what's happening here.
The PermitHelper was designed to approve only the user `amountsIn + slippage` with safety in mind, in the sense that it's safer to approve only what's going to be used instead of the MaxAllowance of MaxUint160.
While the FE opted for convenience, in the sense that user will approve MaxAllowance only once.
I can apply the suggested approach to make sure we never set anything higher than MaxUint160 by mistake, but maybe a better solution is to adapt the PermitHelper to match FE logic.
Since it's an opinionated helper to suit our FE needs, I don't see a reason to have this logic in the SDK (matching user input amounts) that will be overwritten by the FE.
What do you guys think?
cc @agualis @johngrantuk

**Comment by agualis** [comment]
Both options are straightforward to implement for us. I don't thing that other integrators will need those SDK checks so I think it makes sense to remove them until someone really needs them for an alternative ux approach

**Comment by agualis** [comment]
Bruno 19 Nov 20024:
Talking to John we believe that it makes more sense to approve only the amountsIn + slippage within the Permit2 signature.
For that, the FE can simply forward the add liquidity input the user provided.
Any reason why the FE adapted it to max allowance?
Let me know if you guys are ok on making that change or if you’d still rather maximize the allowance.
Thanks!

alberto:
Ok, so our approach for v3 permit2 within V3 was:
the user approves MaxAllowance with 24 hours of expiration
within the next 24 hours they can add any amount of that token (cause MaxAllowance is, in practice, enough to do as much transactions as they want)
Here you can find the implementation for Swaps:
https://github.com/balancer/frontend-monorepo/blob/main/packages/lib/modules/tokens/approvals/permit2/signPermit2Swap.tsx#L64

bruno:
ok, so if you still want to use MaxUint160, all you should do is to set slippage to zero


alberto
I don’t say that this is better that other possible UX alternatives but this is what we (with Pon and Gareth) decided to test
For example, Uniswap uses exact amount for 30 days if I’m not wrong
But we can always change this if we find good arguments

bruno: 
 ok, so if you still want to use MaxUint160, all you should do is to set slippage to zero
In practice, this should work and does not require changes on your side

alberto:
So I would go with this solution and we can have a new discussion if we decide to change the UX, sounds like a plan?

bruno:
I agree it’s best to leave the SDK flexible to accept any input amount from the FE - then you can experiment on your end
just keep in mind that slippage will be applied to the amounts provided
I’ll close the ticket then
